# Generated by Django 2.2.3 on 2019-07-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_voter_id', models.CharField(default='00', max_length=15)),
                ('county_code', models.CharField(default='00', max_length=10)),
                ('election_date', models.CharField(default='00', max_length=15)),
            ],
        ),
    ]
